apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-practice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/choisungwook/argo-rollout-practice.git
    targetRevision: main
    path: example/blue_green
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
