kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argo-practice
nodes:
- role: control-plane
  image: kindest/node:v1.27.2
  extraPortMappings:
  - containerPort: 30950
    hostPort: 30950
- role: worker
  image: kindest/node:v1.27.2